import React from "react";
import { AlertCircle, CheckCircle2, MessageSquare,Lock } from "lucide-react";
import Header from "./../layout/Header";
import Footer from "./../layout/Footer";

export default function Remedies() {
  return (
    <>
      <Header />

      <div className="relative min-h-screen flex items-center justify-center bg-gray-100">
        {/* Blurred Background Overlay */}
        <div className="absolute inset-0 backdrop-blur-md bg-white/15 z-10"></div>

        {/* Payment Access Message */}
        <div className="relative z-20 bg-white/90 rounded-2xl shadow-2xl p-8 max-w-sm text-center">
          <Lock className="w-12 h-12 text-amber-500 mx-auto mb-3" />
          <h2 className="text-lg font-semibold text-gray-900 mb-2">
            Premium Access Required
          </h2>
          <p className="text-sm text-gray-700 mb-5">
            You need to complete your payment to view this personalised
            Astro-Remedy report.
          </p>
          <button className="bg-amber-500 hover:bg-amber-600 transition text-white font-medium px-4 py-2 rounded-lg">
            Proceed to Payment
          </button>
        </div>
      </div>

      {/* <div className="min-h-screen bg-gray-50 text-gray-900 antialiased flex flex-col">
  
        <div className="max-w-6xl mx-auto px-4 pt-6 w-full">
          <div className="text-amber-500 font-medium text-sm mb-4 text-center sm:text-left">
            We have remedies for everything
          </div>
        </div>

        <main className="flex-grow w-full">
          <div className="max-w-6xl mx-auto px-4 pb-12">
            <article className="bg-white rounded-2xl shadow-2xl p-4 sm:p-6 md:p-8">
            
              <div className="mb-6">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between bg-[#F5D9A9] border border-[#EECF9A] rounded-lg px-4 py-3 text-sm text-gray-800 shadow-sm gap-3">
                  <div>
                    <div className="font-semibold">Kushal Shaw</div>
                    <div className="text-xs text-gray-700">Age: 35</div>
                  </div>

                  <div className="flex flex-wrap gap-2 sm:gap-3 text-xs text-gray-700">
                    <span>
                      • Date of birth: <strong className="ml-1">24-12-1986</strong>
                    </span>
                    <span>
                      • Time of birth: <strong className="ml-1">11:45am</strong>
                    </span>
                    <span>
                      • Sign: <strong className="ml-1">Capricorn</strong>
                    </span>
                  </div>
                </div>
              </div>

              <header className="mb-4">
                <h1 className="flex items-center gap-2 sm:gap-3 text-base sm:text-lg md:text-xl font-bold text-gray-900 mb-1">
                  <AlertCircle className="w-5 h-5 text-amber-600 shrink-0" />
                  Your Personalised Astro-Remedy Report
                </h1>

                <div className="text-xs sm:text-sm text-gray-700">
                  Generated by <strong>AI Astro Intelligence Engine™</strong> | Powered by Cosmic Alignment Model v2.9
                </div>
                <div className="text-xs sm:text-sm text-gray-700 mt-2">
                  ✦ Observations from Your Kundli:
                </div>
              </header>

              <p className="text-xs sm:text-sm text-gray-800 mb-4 leading-relaxed">
                Based on your planetary positions at the time of your birth, certain patterns have emerged that are
                currently influencing your mental, emotional, and career energies.
              </p>

              <section className="mb-6">
                <h2 className="flex items-center gap-2 text-black font-semibold mb-3 text-sm sm:text-base">
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    className="inline-block shrink-0"
                  >
                    <circle cx="12" cy="12" r="10" stroke="#C43A2E" strokeWidth="1.2" />
                    <path d="M12 8v5" stroke="#C43A2E" strokeWidth="1.4" strokeLinecap="round" />
                    <circle cx="12" cy="16.3" r="0.6" fill="#C43A2E" />
                  </svg>
                  Detected Issues:
                </h2>

                <ol className="list-decimal ml-5 sm:ml-6 space-y-2 text-xs sm:text-sm text-gray-800">
                  <li>Emotional Overwhelm &amp; Overthinking</li>
                  <li>Moon is slightly afflicted due to its alignment with Rahu, leading to mood instability and emotional sensitivity.</li>
                  <li>Blocked Growth in Career &amp; Finance</li>
                  <li>Saturn’s retrograde aspect in your 10th house is slowing down your momentum, especially in long-term goals.</li>
                  <li>Lack of Stability in Relationships</li>
                  <li>Venus in an unbalanced position is creating temporary misalignments in love and emotional bonds.</li>
                </ol>
              </section>

              <section className="mb-6">
                <h2 className="flex items-center gap-2 text-black font-semibold mb-3 text-sm sm:text-base">
                  <CheckCircle2 className="w-5 h-5 shrink-0" />
                  Remedies for Alignment &amp; Healing:
                </h2>

                <div className="space-y-6 text-xs sm:text-sm text-gray-800 leading-relaxed">
              
                  <div>
                    <h3 className="font-semibold mb-2">1. 🧘 Mind &amp; Emotional Balance</h3>
                    <ul className="list-disc ml-5 sm:ml-6 space-y-1">
                      <li>Every Monday before 9:00 AM, drink lukewarm water infused with tulsi leaves.</li>
                      <li>Meditate facing east for 7 minutes while silently chanting: <em>"Om Chandraya Namaha"</em>.</li>
                      <li>Sleep with a silver coin under your pillow for 11 consecutive nights.</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold mb-2">2. 💼 Career &amp; Financial Unlocking</h3>
                    <ul className="list-disc ml-5 sm:ml-6 space-y-1">
                      <li>On every Saturday evening, light a mustard oil diya under a Peepal tree (or indoors facing west).</li>
                      <li>Keep a piece of black tourmaline crystal near your workspace.</li>
                      <li>Avoid starting new financial tasks on Tuesdays and Saturdays for the next 21 days.</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="font-semibold mb-2">3. ❤️ Relationship Harmony</h3>
                    <ul className="list-disc ml-5 sm:ml-6 space-y-1">
                      <li>Every Friday, wear something white or light pink and avoid arguments post-sunset.</li>
                      <li>Place rose petals soaked in milk in a small copper bowl in the southwest corner of your bedroom.</li>
                      <li>Whisper your desires to a rose quartz crystal and keep it under moonlight once a week.</li>
                    </ul>
                  </div>
                </div>
              </section>

              <p className="text-xs sm:text-sm text-gray-800 mb-6 leading-relaxed">
                ✦ Follow these steps for the next 21 days consistently. Your energetic frequencies will begin to realign, reducing karmic blockages and attracting clarity and harmony.
              </p>

              <p className="text-xs sm:text-sm font-medium mb-4">
                Would you like a version like this for love life, health, marriage timing, or spiritual growth?
              </p>

              <div className="mt-2">
                <div className="flex flex-col sm:flex-row sm:items-center gap-3 bg-white border border-[#E9D3B6] rounded-lg px-3 py-2 sm:px-4 sm:py-3">
                  <div className="flex items-center gap-2 flex-1">
                    <MessageSquare className="w-5 h-5 text-amber-600 shrink-0" />
                    <input
                      type="text"
                      placeholder="Ask Anything"
                      className="flex-1 bg-transparent outline-none text-xs sm:text-sm text-gray-800 placeholder-gray-500"
                    />
                  </div>
                  <button className="bg-amber-400 hover:bg-amber-600 transition text-white text-xs sm:text-sm px-3 py-2 rounded-xl self-end sm:self-auto">
                    Send
                  </button>
                </div>
              </div>
            </article>
          </div>
        </main>
      </div> */}

      <Footer />
    </>
  );
}
